FROM envoyproxy/envoy:v1.14.1

RUN apt-get update && apt-get install -y software-properties-common
RUN add-apt-repository ppa:longsleep/golang-backports
RUN apt install -y golang-go

RUN mkdir /code
ADD ./service/service.go /code
ADD ./start_service.sh /usr/local/bin/start_service.sh
RUN chmod u+x /usr/local/bin/start_service.sh
ENTRYPOINT /usr/local/bin/start_service.sh
